'use strict';

export const TYPES = {
  //appState
  CHANGE_APPSTATE_ATTRIBUTEVALUES:'CHANGE_APPSTATE_ATTRIBUTEVALUES',

  //userinfo
  GET_USERINFO_FROM_SERVER:'GET_USERINFO_FROM_SERVER',
  GET_USERINFO:'GET_USERINFO',
  CHANGE_USERINFO_ATTRIBUTEVALUES:'CHANGE_USERINFO_ATTRIBUTEVALUES',
  ADD_USERINFO_KIDINFO:'ADD_USERINFO_KIDINFO',
  REMOVE_USERINFO_KIDINFO:'REMOVE_USERINFO_KIDINFO',
  EDIT_USERINFO_KIDINFO:'EDIT_USERINFO_KIDINFO'
}
